# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZuO2Ib4TW2U9ruMAGAJfQq1kSSWufMc
"""

!git clone https://github.com/swz30/MPRNet

!mv MPRNet/* ./
!ls
!mkdir data
!mkdir res

!python demo.py --task Denoising --input_dir data/ --result_dir res/